import {randomBytes,randomUUID} from 'node:crypto';
import {db,hash,session,actor,rateLimit,ownProject,transaction,audit} from '@/lib/store';
import {variants,families,finishes,decors,materials,filterCatalog,documents,getVariant} from '@/lib/catalog';
import {projectSchema,requestSchema,draftSchema,approvalSchema} from '@/lib/validation';
import {processOutbox} from '@/lib/adapters';
export const runtime='nodejs';export const dynamic='force-dynamic';
type Context={params:Promise<{path:string[]}>};
async function handler(req:Request,ctx:Context){const p=(await ctx.params).path;const url=new URL(req.url);const s=session(req);const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store','Referrer-Policy':'no-referrer',...(s.cookie?{'Set-Cookie':s.cookie}:{})}});const fail=(message:string,status=400)=>json({error:message},status);try{
if(req.method!=='GET'&&req.headers.get('origin')&&req.headers.get('origin')!==(process.env.FD_PUBLIC_ORIGIN||'http://127.0.0.1:4173'))return fail('Origin is not allowed',403);
if(!rateLimit(`global:${p[0]}`,p[0]==='enquiries'?100:1000))return fail('Local service is busy. Please retry shortly.',429);
if(!rateLimit(`${s.owner}:${p[0]}`,p[0]==='enquiries'?12:60))return fail('Too many requests. Please try again shortly.',429);
let body:any=null;if(req.method!=='GET'){if(!req.headers.get('content-type')?.includes('application/json'))return fail('JSON required',415);if(Number(req.headers.get('content-length')||0)>16384)return fail('Request is too large',413);const reader=req.body?.getReader();let raw='',bytes=0;if(reader){const decoder=new TextDecoder();while(true){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.length;if(bytes>16384){await reader.cancel();return fail('Request is too large',413)}raw+=decoder.decode(chunk.value,{stream:true})}raw+=decoder.decode()}try{body=JSON.parse(raw)}catch{return fail('Invalid JSON')}}
if(p[0]==='catalog'&&req.method==='GET'){const q=url.searchParams.get('q')||'',finish=url.searchParams.get('finish')||'all',colour=url.searchParams.get('colour')||'all',family=url.searchParams.get('family')||'all';if(q.length>80||!['all','frosted','gloss'].includes(finish)||!['all','green','grey','neutral'].includes(colour)||!['all','unassigned','fineflex','lacquered-laminate'].includes(family))return fail('Unsupported catalog filter');return json({variants:filterCatalog(variants,q,finish,colour,family).map(v=>{const r=db().prepare("SELECT payload FROM ContentRevision WHERE variant_id=? AND status='published-demo' ORDER BY created_at DESC LIMIT 1").get(v.id);return r?{...v,editorialNote:JSON.parse(r.payload as string).editorialLabel}:v}),decors,finishes,families,materials,mode:'local-demo'})}
if(p[0]==='projects'){
if(p.length===1&&req.method==='GET'){return json({projects:db().prepare('SELECT id,payload,created_at FROM Project WHERE owner_hash=? ORDER BY updated_at DESC').all(s.owner).map(r=>({id:r.id,...JSON.parse(r.payload as string),createdAt:r.created_at}))})}
if(p.length===1&&req.method==='POST'){const v=projectSchema.safeParse(body);if(!v.success)return fail(v.error.issues.map(x=>x.message).join('; '));const id=randomUUID(),now=new Date().toISOString();db().prepare('INSERT INTO Project VALUES(?,?,?,?,?)').run(id,s.owner,JSON.stringify(v.data),now,now);audit('anonymous','project-created',id);return json({id,...v.data,createdAt:now,private:true},201)}
const project=ownProject(p[1],s.owner);if(!project)return fail('Project not found for this browser',404);
if(p.length===2&&req.method==='GET')return json({id:project.id,...JSON.parse(project.payload),createdAt:project.created_at});
if(p[2]==='share'&&req.method==='POST'){if(body?.acknowledgeVisible!==true||Object.keys(body).length!==1)return fail('Confirm that variant IDs, name, scene, lighting and camera will be visible.');const token=randomBytes(32).toString('hex'),now=new Date().toISOString();db().prepare('INSERT INTO ShareToken VALUES(?,?,?,?,NULL)').run(hash(token),project.id,now,new Date(Date.now()+30*86400000).toISOString());audit('anonymous','project-shared',project.id);return json({token,expiresInDays:30},201)}
if(p[2]==='revoke'&&req.method==='POST'){db().prepare('UPDATE ShareToken SET revoked_at=? WHERE project_id=? AND revoked_at IS NULL').run(new Date().toISOString(),project.id);audit('anonymous','project-share-revoked',project.id);return json({revoked:true})}
}
if(p[0]==='shares'&&req.method==='GET'){if(!/^[a-f0-9]{64}$/.test(p[1]||''))return fail('Shared project unavailable',404);const r=db().prepare('SELECT p.id,p.payload,p.created_at FROM ShareToken s JOIN Project p ON p.id=s.project_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>?').get(hash(p[1]),new Date().toISOString());if(!r)return fail('This link has expired or was revoked.',404);const payload=JSON.parse(r.payload as string);return json({id:r.id,...payload,createdAt:r.created_at,shared:true,missingVariantIds:payload.variantIds.filter((x:string)=>!getVariant(x))})}
if(p[0]==='enquiries'&&req.method==='POST'){const v=requestSchema.safeParse(body);if(!v.success)return fail(v.error.issues.map(x=>x.message).join('; '));const value=v.data;if(value.projectId&&!ownProject(value.projectId,s.owner))return fail('Project does not belong to this browser',403);const project=value.projectId?ownProject(value.projectId,s.owner):null;if(project&&!value.variantIds.every(x=>JSON.parse(project.payload).variantIds.includes(x)))return fail('Selected variants do not match saved project');const payload={...value,demo:true,fulfilmentBlocked:true};delete (payload as any).website;const h=hash(JSON.stringify(payload));const old=db().prepare('SELECT id,body_hash FROM SampleRequest WHERE owner_hash=? AND idempotency_key=?').get(s.owner,value.idempotencyKey);if(old)return old.body_hash===h?json({id:old.id,demo:true,duplicate:true,status:'saved-for-local-review'}):fail('This request key was already used for different details',409);const id=randomUUID(),now=new Date().toISOString();transaction(()=>{db().prepare('INSERT INTO SampleRequest(id,owner_hash,idempotency_key,payload,body_hash,created_at) VALUES(?,?,?,?,?,?)').run(id,s.owner,value.idempotencyKey,JSON.stringify(payload),h,now);for(const adapter of ['crm','warehouse','email'])db().prepare('INSERT INTO Outbox(id,request_id,adapter,status) VALUES(?,?,?,?)').run(randomUUID(),id,adapter,'pending');audit('anonymous','enquiry-stored',id)});return json({id,demo:true,status:'saved-for-local-review',fulfilmentBlocked:true},201)}
if(p[0]==='documents'&&req.method==='GET'){const doc=documents.find(d=>d.id===p[1]);if(!doc)return fail('No current approved document is available',404);if((!doc.public||doc.approval!=='approved')&&!actor(req))return fail('Document access requires authorization',403);return json(doc)}
if(p[0]==='admin'){
const role=actor(req);if(!role)return fail('Admin access requires a valid role token',401);
if(req.method==='GET')return json({role,revisions:db().prepare('SELECT * FROM ContentRevision ORDER BY created_at DESC').all(),audit:db().prepare('SELECT * FROM AuditEvent ORDER BY created_at DESC LIMIT 50').all(),outbox:db().prepare('SELECT id,adapter,status,attempts,last_error,next_attempt FROM Outbox').all(),counts:{enquiries:db().prepare('SELECT COUNT(*) AS n FROM SampleRequest').get()?.n}});
if(p[1]==='drafts'&&req.method==='POST'){if(!['editor','administrator'].includes(role))return fail('Editor role required',403);const v=draftSchema.safeParse(body);if(!v.success)return fail('Invalid draft');const id=randomUUID();db().prepare('INSERT INTO ContentRevision VALUES(?,?,?,?,?,?,?,?)').run(id,v.data.variantId,JSON.stringify(v.data),'draft',role,null,null,new Date().toISOString());audit(role,'draft-created',id);return json({id,status:'draft'},201)}
if(p[1]==='review'&&req.method==='POST'){if(role!=='technical')return fail('Independent technical approver required',403);const {id,...rest}=body||{};if(typeof id!=='string'||id.length>80)return fail('Invalid revision ID');const v=approvalSchema.safeParse(rest);if(!v.success)return fail('Evidence, version, dates, rights and scope confirmations are required');const r=db().prepare('SELECT * FROM ContentRevision WHERE id=? AND status=?').get(id,'draft');if(!r)return fail('Draft not found',404);db().prepare('UPDATE ContentRevision SET status=?,reviewed_by=?,review_payload=? WHERE id=?').run(v.data.decision==='approve'?'approved':'held',role,JSON.stringify(v.data),id);audit(role,'technical-'+v.data.decision,id);return json({approved:v.data.decision==='approve'})}
if(p[1]==='publish'&&req.method==='POST'){if(role!=='administrator')return fail('Administrator role required',403);if(typeof body?.id!=='string'||body.id.length>80)return fail('Invalid revision ID');const r=db().prepare("SELECT * FROM ContentRevision WHERE id=? AND status='approved'").get(body?.id);if(!r||!r.reviewed_by||!r.review_payload)return fail('Technical approval is required before publication',409);db().prepare("UPDATE ContentRevision SET status='published-demo' WHERE id=?").run(body.id);audit(role,'demo-revision-published',body.id);return json({published:true,demo:true,fulfilmentBlocked:true})}
if(p[1]==='retry'&&req.method==='POST'){if(role!=='administrator')return fail('Administrator role required',403);db().prepare("UPDATE Outbox SET status='pending',attempts=0,next_attempt=NULL WHERE status='failed'").run();return json(await processOutbox(body?.simulate===true))}
}
return fail('Endpoint not found',404);
}catch(e){if(e instanceof Error&&e.message.includes('SQLITE'))return fail('Local storage is unavailable. Keep your details and try again.',503);return fail('The request could not be completed. Please retry or contact Fine Decor.',500)}}
export const GET=handler;export const POST=handler;
