'use client';
import {createContext,useContext,useEffect,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import {variants as seed,getVariant} from '@/lib/catalog';
import type {ProductVariant,Project} from '@/lib/model';
type Library={items:ProductVariant[];shortlist:string[];toggle:(id:string)=>void;add:(ids:string[])=>void;message:(s:string)=>void;project:Project|null;setProject:(p:Project|null)=>boolean;projectId:string|null;setProjectId:(id:string|null)=>void;enquiryId:string|null;setEnquiryId:(id:string|null)=>void;storageStatus:string;ready:boolean;serverPersistence:boolean;studioMode:'2d'|'3d';setStudioMode:(mode:'2d'|'3d')=>void};
const Context=createContext<Library|null>(null);
// The full Studio opens in 3D by request; a 2D choice lasts for this visit. Text and source swatches still render before the deferred renderer.
export function LibraryProvider({children,serverPersistence=true}:{children:React.ReactNode;serverPersistence?:boolean}){const pathname=usePathname(),previousPath=useRef(pathname);useEffect(()=>{if(previousPath.current===pathname)return;previousPath.current=pathname;const frame=requestAnimationFrame(()=>document.getElementById('main')?.focus({preventScroll:true}));return ()=>cancelAnimationFrame(frame)},[pathname]);const [items,setItems]=useState(seed),[shortlist,setShortlist]=useState<string[]>([]),[toast,setToast]=useState(''),[project,setProject]=useState<Project|null>(null),[projectId,setProjectId]=useState<string|null>(null),[enquiryId,setEnquiryId]=useState<string|null>(null),[storageStatus,setStorageStatus]=useState('');
const [ready,setReady]=useState(false),[studioMode,setStudioMode]=useState<'2d'|'3d'>('3d');
useEffect(()=>{try{const ids=JSON.parse(localStorage.getItem('fd-shortlist')||'[]');if(Array.isArray(ids))setShortlist(ids.filter(x=>typeof x==='string'&&getVariant(x)).slice(0,12));const p=JSON.parse(localStorage.getItem('fd-project')||'null');if(p&&Array.isArray(p.variantIds))setProject(p);setProjectId(localStorage.getItem('fd-project-id'));setEnquiryId(localStorage.getItem('fd-enquiry-id'))}catch{setStorageStatus('Device storage is unavailable. You can still browse and send a local enquiry.')}setReady(true);
fetch('/api/catalog').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setItems(d.variants)).catch(()=>setStorageStatus('Catalog connection unavailable. Showing the verified demo snapshot.'))},[]);
const persist=(ids:string[])=>{setShortlist(ids);try{localStorage.setItem('fd-shortlist',JSON.stringify(ids))}catch{setStorageStatus('Your shortlist can only be kept for this visit.')}};
const limitMessage=()=>setToast(pathname.startsWith('/de')?'Bis zu 12 Referenzen auf der Merkliste. Entfernen Sie zuerst eine Referenz.':'Your shortlist holds up to 12 references. Remove one before adding another.');
const toggle=(id:string)=>{if(!getVariant(id))return;const found=shortlist.includes(id);if(!found&&shortlist.length>=12){limitMessage();return}persist(found?shortlist.filter(x=>x!==id):[...shortlist,id]);setToast(found?'Removed from shortlist':'Added to shortlist')};const add=(ids:string[])=>{const next=Array.from(new Set([...shortlist,...ids.filter(x=>getVariant(x))]));if(next.length>12){limitMessage();return}persist(next)};
const updateProject=(p:Project|null)=>{setProject(p);try{localStorage.setItem('fd-project',JSON.stringify(p));return true}catch{setStorageStatus(serverPersistence?'Device storage is unavailable. Keep a private saved snapshot before leaving.':'Device storage is unavailable. This draft is held only for this visit.');return false}};const updateId=(id:string|null)=>{setProjectId(id);try{id?localStorage.setItem('fd-project-id',id):localStorage.removeItem('fd-project-id');localStorage.removeItem('fd-enquiry-id')}catch{}setEnquiryId(null)};const updateEnquiry=(id:string|null)=>{setEnquiryId(id);try{id?localStorage.setItem('fd-enquiry-id',id):localStorage.removeItem('fd-enquiry-id')}catch{}};
useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4500);return ()=>clearTimeout(timer)}},[toast]);
return <Context.Provider value={{items,shortlist,toggle,add,message:setToast,project,setProject:updateProject,projectId,setProjectId:updateId,enquiryId,setEnquiryId:updateEnquiry,storageStatus,ready,serverPersistence,studioMode,setStudioMode}}>{children}<output className={`toast ${toast?'show':''}`} aria-live="polite" aria-atomic="true">{toast}</output></Context.Provider>}
export const useLibrary=()=>useContext(Context)!;
