import {applicationImagery} from './application-imagery';
import {productionDecors,productionVariants,productionMaterials} from './production-catalog';
import type {ProductVariant,Decor,Finish,ProductFamily,Application,MaterialAsset,Office,NewsArticle,TechnicalDocument,ClaimEvidence} from './model';
export const PRODUCT_SOURCE='https://www.finedecor.de/en/our-products/';
export const families:ProductFamily[]=[{id:'fineflex',name:'Fineflex',description:'PET decorative surface range referenced on the public website. Variant compatibility needs owner approval.',approval:'draft'},{id:'lacquered-laminate',name:'Lacquered laminate',description:'Public range reference. Current technical scope is under review.',approval:'draft'}];
export const decors:Decor[]=[{id:'d373',code:'373',name:'OliveGreen',colourFamily:'green',source:PRODUCT_SOURCE},{id:'d255',code:'255',name:'Kaschmir',colourFamily:'neutral',source:PRODUCT_SOURCE},{id:'d1121',code:'1121',name:'Sand',colourFamily:'neutral',source:PRODUCT_SOURCE},{id:'d425',code:'425',name:'SlateGrey',colourFamily:'grey',source:PRODUCT_SOURCE},...productionDecors.filter(d=>!['d373','d255','d1121','d425'].includes(d.id))];
export const finishes:Finish[]=[{id:'frosted',name:'Frosted',description:'Finish label as listed by Fine Decor. Illustrative matte response in the studio.'},{id:'gloss',name:'Gloss',description:'Finish label as listed by Fine Decor. Illustrative glossy response in the studio.'}];
export const variants:ProductVariant[]=[...[['d373','frosted','#747b54'],['d255','frosted','#b3a998'],['d1121','frosted','#d4cab3'],['d425','frosted','#5b625b'],['d373','gloss','#737956'],['d425','gloss','#4f5550']].map(([decorId,finishId,hex])=>({id:`demo-${decorId.slice(1)}-${finishId}`,decorId,finishId,familyId:null,sku:null,approval:'draft' as const,demo:true,compatibleApplications:[],dimensions:null,documentIds:[],materialId:`illustrative-${finishId}`,swatch:`/media/swatches/${decorId.slice(1)}-${finishId}.jpg`,hex})),...productionVariants];
export const materials:MaterialAsset[]=[...finishes.map(f=>({id:`illustrative-${f.id}`,variantIds:variants.filter(v=>v.finishId===f.id&&v.materialId===`illustrative-${f.id}`).map(v=>v.id),baseColourUrl:null,normalUrl:null,roughnessUrl:null,clearcoatUrl:null,provenance:'Manually selected illustrative colour. Source swatch remains a separate 2D reference; no measured texture maps supplied.',scaleMetres:null,colourSpace:'sRGB' as const,uvOrientation:null,calibrationStatus:'illustrative' as const,visualParameters:{roughness:f.id==='gloss'?.16:.72,clearcoat:f.id==='gloss'?.75:.08,metalness:0}})),...productionMaterials];
export const applications:Application[]=[['kitchens','Kitchens','Küchen'],['living','Living furniture','Wohnmöbel'],['bathroom','Bathroom furniture','Badmöbel'],['shopfitting','Shopfitting','Ladenbau'],['doors','Doors','Türen'],['caravans','Caravans','Caravans']].map(([id,en,de])=>({id,name:{en,de},source:PRODUCT_SOURCE,variantIds:[]}));
export const documents:TechnicalDocument[]=[];
export const evidence:ClaimEvidence[]=[{id:'founded-2004',approvedWording:null,source:'https://www.finedecor.de/en/about-fine-decor/',scope:['company-history'],approval:'draft',reviewDate:null}];
export const offices:Office[]=[{id:'oelde',name:'Head office / production',address:'Aurea 21, 59302 Oelde, Germany',phone:'+49 2522 937 97 0',email:'info@finedecor.de',responsibilities:null,approval:'in-review',source:'https://www.finedecor.de/en/about-fine-decor/'},{id:'bielefeld',name:'Warehouse',address:'Am Niedermeyers Feld 8, 33719 Bielefeld, Germany',phone:null,email:null,responsibilities:null,approval:'in-review',source:'https://www.finedecor.de/en/about-fine-decor/'},{id:'istanbul',name:'Istanbul branch',address:'Istanbul, Türkiye · exact current address pending review',phone:null,email:null,responsibilities:null,approval:'in-review',source:'https://www.finedecor.com.tr/hakkimizda'}];
export const news:NewsArticle[]=[{id:'participation-2024',title:{en:'Schattdecor participation ended in June 2024',de:'Schattdecor-Beteiligung endete im Juni 2024'},date:'2024-06-21',source:'https://www.schattdecor.com/en/news/dissolution-of-the-participation',archived:true},{id:'interzum-2023',title:{en:'From the archive: Interzum 2023',de:'Aus dem Archiv: Interzum 2023'},date:'2023',source:'https://www.finedecor.de/en/pr-events/',archived:true}];
export const getVariant=(id:string)=>variants.find(v=>v.id===id);
export const getDecor=(v:ProductVariant)=>decors.find(d=>d.id===v.decorId)!;
export const getFinish=(v:ProductVariant)=>finishes.find(f=>f.id===v.finishId)!;
export function filterCatalog(items:ProductVariant[],q='',finish='all',colour='all',family='all'){return items.filter(v=>{const d=getDecor(v);return `${d.name} ${d.code} ${v.id}`.toLowerCase().includes(q.toLowerCase().trim())&&(finish==='all'||finish===v.finishId)&&(colour==='all'||colour===d.colourFamily)&&(family==='all'||(family==='unassigned'?v.familyId===null:v.familyId===family))})}
export const defaultCamera={preset:'perspective' as const,position:[3.5,2.6,4.8] as [number,number,number],target:[0,1.05,0] as [number,number,number]};
export const defaultProject={name:'Untitled surface study',variantIds:[variants[0].id],assignments:{fronts:variants[0].id},scene:'panel' as const,light:'neutral' as const,camera:defaultCamera,compareId:null};

export const mediaAssets=[{id:'source-kitchen',url:'/media/kitchen.jpg',source:'https://www.finedecor.de/en/',rights:'user-authorized-local-demo',type:'photograph',approved:false},{id:'source-company-facade',url:'/media/interior.jpg',source:'https://www.finedecor.de/en/',rights:'user-authorized-local-demo',type:'photograph',approved:false},{id:'source-production-rolls',url:'/media/production-rolls.jpg',source:'https://www.finedecor.de/en/',rights:'user-authorized-local-demo',type:'photograph',approved:false},{id:'source-production-workshop',url:'/media/production.jpg',source:'https://www.finedecor.de/ueber-fine-decor/',rights:'user-authorized-local-demo',type:'photograph',approved:false},{id:'source-fineline-aerial',url:'/media/source-production-hall.jpg',source:'https://www.finedecor.de/en/about-fine-decor/',rights:'user-authorized-site-review',type:'photograph',approved:false},{id:'source-fineline-exterior',url:'/media/source-production-exterior.jpg',source:'https://www.finedecor.de/en/about-fine-decor/',rights:'user-authorized-site-review',type:'photograph',approved:false},...Object.values(applicationImagery).filter(image=>image.kind==='inspiration').map(image=>({id:image.id,url:image.src,source:image.source,rights:image.license!,type:'photograph',approved:false})),...variants.map(v=>({id:'swatch-'+v.id,url:v.swatch,source:PRODUCT_SOURCE,rights:'user-authorized-local-demo',type:'swatch',approved:false}))];
