import type {Decor, ProductVariant} from './model';

// Checked against both rendered production finish tabs on 4 October 2026.
// These public-source references remain demos pending owner product approval.
export const PRODUCTION_CATALOG_SOURCE = 'https://www.finedecor.de/en/our-products/';
export const PRODUCTION_CATALOG_REVIEW_DATE = '2026-10-04';
export interface ProductionCatalogEntry {
  id: string; code: string; name: string; finish: 'frosted' | 'gloss';
  decorId: string; colourFamily: Decor['colourFamily']; swatch: string;
  displayHex: string; sourceImageUrl: string; sourceLabel: string; legacyPreserved: boolean;
}
export const productionSourceEntries: ProductionCatalogEntry[] = [
  {
    "id": "demo-101-frosted",
    "code": "101",
    "name": "White",
    "finish": "frosted",
    "decorId": "d101",
    "colourFamily": "white",
    "swatch": "/media/swatches/101-frosted.jpg",
    "displayHex": "#ebeae5",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/01_101-White.jpg",
    "sourceLabel": "101-White",
    "legacyPreserved": false
  },
  {
    "id": "demo-245-frosted",
    "code": "245",
    "name": "Polarweiss",
    "finish": "frosted",
    "decorId": "d245",
    "colourFamily": "white",
    "swatch": "/media/swatches/245-frosted.jpg",
    "displayHex": "#e9e7ea",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/02_245-Polarweiss.jpg",
    "sourceLabel": "245-Polarweiss",
    "legacyPreserved": false
  },
  {
    "id": "demo-546-frosted",
    "code": "546",
    "name": "White",
    "finish": "frosted",
    "decorId": "d546",
    "colourFamily": "white",
    "swatch": "/media/swatches/546-frosted.jpg",
    "displayHex": "#f5f7f4",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/03_546-White.jpg",
    "sourceLabel": "546-White",
    "legacyPreserved": false
  },
  {
    "id": "demo-540-frosted",
    "code": "540",
    "name": "Alpinweiss",
    "finish": "frosted",
    "decorId": "d540",
    "colourFamily": "white",
    "swatch": "/media/swatches/540-frosted.jpg",
    "displayHex": "#f1f1ef",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/04_540-Alpinweiss.jpg",
    "sourceLabel": "540-Alpinweiss",
    "legacyPreserved": false
  },
  {
    "id": "demo-191-frosted",
    "code": "191",
    "name": "Kristallweiss",
    "finish": "frosted",
    "decorId": "d191",
    "colourFamily": "white",
    "swatch": "/media/swatches/191-frosted.jpg",
    "displayHex": "#eff1ee",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/05_191-Kristallweiss.jpg",
    "sourceLabel": "191-Kristallweiss",
    "legacyPreserved": false
  },
  {
    "id": "demo-548-1-frosted",
    "code": "548-1",
    "name": "VistaWhite",
    "finish": "frosted",
    "decorId": "d548-1",
    "colourFamily": "white",
    "swatch": "/media/swatches/548-1-frosted.jpg",
    "displayHex": "#ebebe1",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/06_548-1-VistaWhite.jpg",
    "sourceLabel": "548-1-VistaWhite",
    "legacyPreserved": false
  },
  {
    "id": "demo-243-frosted",
    "code": "243",
    "name": "Weiss",
    "finish": "frosted",
    "decorId": "d243",
    "colourFamily": "white",
    "swatch": "/media/swatches/243-frosted.jpg",
    "displayHex": "#f0eee2",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/07_243-Weiss.jpg",
    "sourceLabel": "243-Weiss",
    "legacyPreserved": false
  },
  {
    "id": "demo-1120-frosted",
    "code": "1120",
    "name": "White",
    "finish": "frosted",
    "decorId": "d1120",
    "colourFamily": "white",
    "swatch": "/media/swatches/1120-frosted.jpg",
    "displayHex": "#f0eee1",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/08_1120-White.jpg",
    "sourceLabel": "1120-White",
    "legacyPreserved": false
  },
  {
    "id": "demo-244-frosted",
    "code": "244",
    "name": "Magnolie",
    "finish": "frosted",
    "decorId": "d244",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/244-frosted.jpg",
    "displayHex": "#efe7da",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/09_244-Magnolie.jpg",
    "sourceLabel": "244-Magnolie",
    "legacyPreserved": false
  },
  {
    "id": "demo-8362-frosted",
    "code": "8362",
    "name": "Magnolia",
    "finish": "frosted",
    "decorId": "d8362-magnolia",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/8362-frosted.jpg",
    "displayHex": "#ede4d5",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/10_8362-Magnolia.jpg",
    "sourceLabel": "8362-Magnolia",
    "legacyPreserved": false
  },
  {
    "id": "demo-254-frosted",
    "code": "254",
    "name": "Avorio",
    "finish": "frosted",
    "decorId": "d254",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/254-frosted.jpg",
    "displayHex": "#e4ddcd",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/11_254-Avorio.jpg",
    "sourceLabel": "254-Avorio",
    "legacyPreserved": false
  },
  {
    "id": "demo-301-frosted",
    "code": "301",
    "name": "Cream",
    "finish": "frosted",
    "decorId": "d301",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/301-frosted.jpg",
    "displayHex": "#e9dbc0",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/12_301-Cream.jpg",
    "sourceLabel": "301-Cream",
    "legacyPreserved": false
  },
  {
    "id": "demo-255-frosted",
    "code": "255",
    "name": "Kaschmir",
    "finish": "frosted",
    "decorId": "d255",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/255-frosted.jpg",
    "displayHex": "#b3a998",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/13_255-Kaschmir.jpg",
    "sourceLabel": "255-Kaschmir",
    "legacyPreserved": true
  },
  {
    "id": "demo-8370-frosted",
    "code": "8370",
    "name": "Lux-Sahara",
    "finish": "frosted",
    "decorId": "d8370",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/8370-frosted.jpg",
    "displayHex": "#cbc2b9",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/14_8370-Lux-Sahara.jpg",
    "sourceLabel": "8370-Lux-Sahara",
    "legacyPreserved": false
  },
  {
    "id": "demo-1121-frosted",
    "code": "1121",
    "name": "Sand",
    "finish": "frosted",
    "decorId": "d1121",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/1121-frosted.jpg",
    "displayHex": "#d4cab3",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/15_1121-Sand.jpg",
    "sourceLabel": "1121-Sand",
    "legacyPreserved": true
  },
  {
    "id": "demo-1130-frosted",
    "code": "1130",
    "name": "Savanne",
    "finish": "frosted",
    "decorId": "d1130",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/1130-frosted.jpg",
    "displayHex": "#d2cec3",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/16_1130-Savanne.jpg",
    "sourceLabel": "1130-Savanne",
    "legacyPreserved": false
  },
  {
    "id": "demo-1124-frosted",
    "code": "1124",
    "name": "Kieselgrau",
    "finish": "frosted",
    "decorId": "d1124",
    "colourFamily": "grey",
    "swatch": "/media/swatches/1124-frosted.jpg",
    "displayHex": "#c9c3b7",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/17_1124-Kieselgrau.jpg",
    "sourceLabel": "1124-Kieselgrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-449-frosted",
    "code": "449",
    "name": "ShellGrey",
    "finish": "frosted",
    "decorId": "d449",
    "colourFamily": "grey",
    "swatch": "/media/swatches/449-frosted.jpg",
    "displayHex": "#beb8a8",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/18_449-ShellGrey.jpg",
    "sourceLabel": "449-ShellGrey",
    "legacyPreserved": false
  },
  {
    "id": "demo-246-frosted",
    "code": "246",
    "name": "Kaschmir",
    "finish": "frosted",
    "decorId": "d246",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/246-frosted.jpg",
    "displayHex": "#c0b3aa",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/19_246-Kaschmir.jpg",
    "sourceLabel": "246-Kaschmir",
    "legacyPreserved": false
  },
  {
    "id": "demo-1126-frosted",
    "code": "1126",
    "name": "SandGrau",
    "finish": "frosted",
    "decorId": "d1126",
    "colourFamily": "grey",
    "swatch": "/media/swatches/1126-frosted.jpg",
    "displayHex": "#a09488",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/20_1126-SandGrau.jpg",
    "sourceLabel": "1126-SandGrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-247-frosted",
    "code": "247",
    "name": "BasaltGrau",
    "finish": "frosted",
    "decorId": "d247",
    "colourFamily": "grey",
    "swatch": "/media/swatches/247-frosted.jpg",
    "displayHex": "#877d74",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/21_247-BasaltGrau.jpg",
    "sourceLabel": "247-BasaltGrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-477-frosted",
    "code": "477",
    "name": "Cacao",
    "finish": "frosted",
    "decorId": "d477",
    "colourFamily": "brown",
    "swatch": "/media/swatches/477-frosted.jpg",
    "displayHex": "#73665e",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/22_477-Cacao.jpg",
    "sourceLabel": "477-Cacao",
    "legacyPreserved": false
  },
  {
    "id": "demo-392-frosted",
    "code": "392",
    "name": "HazelnutRed",
    "finish": "frosted",
    "decorId": "d392",
    "colourFamily": "brown",
    "swatch": "/media/swatches/392-frosted.jpg",
    "displayHex": "#705b58",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/23_392-HazelnutRed.jpg",
    "sourceLabel": "392-HazelnutRed",
    "legacyPreserved": false
  },
  {
    "id": "demo-577-frosted",
    "code": "577",
    "name": "BlackBrown",
    "finish": "frosted",
    "decorId": "d577",
    "colourFamily": "brown",
    "swatch": "/media/swatches/577-frosted.jpg",
    "displayHex": "#574d4b",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/24_577-BlackBrown.jpg",
    "sourceLabel": "577-BlackBrown",
    "legacyPreserved": false
  },
  {
    "id": "demo-962-frosted",
    "code": "962",
    "name": "Hellgrau",
    "finish": "frosted",
    "decorId": "d962",
    "colourFamily": "grey",
    "swatch": "/media/swatches/962-frosted.jpg",
    "displayHex": "#cac9c7",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/25_962-Hellgrau.jpg",
    "sourceLabel": "962-Hellgrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-570-frosted",
    "code": "570",
    "name": "GrigioSeta",
    "finish": "frosted",
    "decorId": "d570-grigioseta",
    "colourFamily": "grey",
    "swatch": "/media/swatches/570-frosted.jpg",
    "displayHex": "#d2cfca",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/26_570-GrigioSeta.jpg",
    "sourceLabel": "570-GrigioSeta",
    "legacyPreserved": false
  },
  {
    "id": "demo-423-frosted",
    "code": "423",
    "name": "NavyGrey",
    "finish": "frosted",
    "decorId": "d423",
    "colourFamily": "grey",
    "swatch": "/media/swatches/423-frosted.jpg",
    "displayHex": "#b3b4af",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/27_423-NavyGrey.jpg",
    "sourceLabel": "423-NavyGrey",
    "legacyPreserved": false
  },
  {
    "id": "demo-421-frosted",
    "code": "421",
    "name": "PapayrusGrey",
    "finish": "frosted",
    "decorId": "d421",
    "colourFamily": "grey",
    "swatch": "/media/swatches/421-frosted.jpg",
    "displayHex": "#999ea1",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/28_421-PapayrusGrey.jpg",
    "sourceLabel": "421-PapayrusGrey",
    "legacyPreserved": false
  },
  {
    "id": "demo-314-frosted",
    "code": "314",
    "name": "StahlGrau",
    "finish": "frosted",
    "decorId": "d314",
    "colourFamily": "grey",
    "swatch": "/media/swatches/314-frosted.jpg",
    "displayHex": "#a7a6a2",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/30_314-StahlGrau.jpg",
    "sourceLabel": "314-StahlGrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-412-frosted",
    "code": "412",
    "name": "GrisGarlet",
    "finish": "frosted",
    "decorId": "d412-grisgarlet",
    "colourFamily": "grey",
    "swatch": "/media/swatches/412-frosted.jpg",
    "displayHex": "#969694",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/31_412-GrisGarlet.jpg",
    "sourceLabel": "412-GrisGarlet",
    "legacyPreserved": false
  },
  {
    "id": "demo-1127-frosted",
    "code": "1127",
    "name": "Steingrau",
    "finish": "frosted",
    "decorId": "d1127",
    "colourFamily": "grey",
    "swatch": "/media/swatches/1127-frosted.jpg",
    "displayHex": "#828483",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/32_1127-Steingrau.jpg",
    "sourceLabel": "1127-Steingrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-4270-frosted",
    "code": "4270",
    "name": "QuarzGrau",
    "finish": "frosted",
    "decorId": "d4270",
    "colourFamily": "grey",
    "swatch": "/media/swatches/4270-frosted.jpg",
    "displayHex": "#6b6a68",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/33_4270-QuarzGrau.jpg",
    "sourceLabel": "4270-QuarzGrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-105-frosted",
    "code": "105",
    "name": "ShadowGrey",
    "finish": "frosted",
    "decorId": "d105",
    "colourFamily": "grey",
    "swatch": "/media/swatches/105-frosted.jpg",
    "displayHex": "#5a5957",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/34_105-ShadowGrey.jpg",
    "sourceLabel": "105-ShadowGrey",
    "legacyPreserved": false
  },
  {
    "id": "demo-422-frosted",
    "code": "422",
    "name": "Schiefergrau",
    "finish": "frosted",
    "decorId": "d422",
    "colourFamily": "grey",
    "swatch": "/media/swatches/422-frosted.jpg",
    "displayHex": "#5c5c5a",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/35_422-Schiefergrau.jpg",
    "sourceLabel": "422-Schiefergrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-425-frosted",
    "code": "425",
    "name": "SlateGrey",
    "finish": "frosted",
    "decorId": "d425",
    "colourFamily": "grey",
    "swatch": "/media/swatches/425-frosted.jpg",
    "displayHex": "#5b625b",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/36_425-SlateGrey.jpg",
    "sourceLabel": "425-SlateGrey",
    "legacyPreserved": true
  },
  {
    "id": "demo-1128-frosted",
    "code": "1128",
    "name": "Terra",
    "finish": "frosted",
    "decorId": "d1128",
    "colourFamily": "brown",
    "swatch": "/media/swatches/1128-frosted.jpg",
    "displayHex": "#3f3a37",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/37_1128-Terra.jpg",
    "sourceLabel": "1128-Terra",
    "legacyPreserved": false
  },
  {
    "id": "demo-5000-frosted",
    "code": "5000",
    "name": "Black",
    "finish": "frosted",
    "decorId": "d5000",
    "colourFamily": "black",
    "swatch": "/media/swatches/5000-frosted.jpg",
    "displayHex": "#353535",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/38_5000-Black.jpg",
    "sourceLabel": "5000-Black",
    "legacyPreserved": false
  },
  {
    "id": "demo-567-frosted",
    "code": "567",
    "name": "Black",
    "finish": "frosted",
    "decorId": "d567",
    "colourFamily": "black",
    "swatch": "/media/swatches/567-frosted.jpg",
    "displayHex": "#303030",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/39_567-Black.jpg",
    "sourceLabel": "567-Black",
    "legacyPreserved": false
  },
  {
    "id": "demo-505-2-frosted",
    "code": "505-2",
    "name": "IndigoBlue",
    "finish": "frosted",
    "decorId": "d505-2",
    "colourFamily": "blue",
    "swatch": "/media/swatches/505-2-frosted.jpg",
    "displayHex": "#2e3339",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/40_505-2-IndigoBlue.jpg",
    "sourceLabel": "505-2-IndigoBlue",
    "legacyPreserved": false
  },
  {
    "id": "demo-373-frosted",
    "code": "373",
    "name": "OliveGreen",
    "finish": "frosted",
    "decorId": "d373",
    "colourFamily": "green",
    "swatch": "/media/swatches/373-frosted.jpg",
    "displayHex": "#747b54",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/41_373-OliveGreen.jpg",
    "sourceLabel": "373-OliveGreen",
    "legacyPreserved": true
  },
  {
    "id": "demo-388-frosted",
    "code": "388",
    "name": "AmazonGreen",
    "finish": "frosted",
    "decorId": "d388",
    "colourFamily": "green",
    "swatch": "/media/swatches/388-frosted.jpg",
    "displayHex": "#64706e",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/42_388-AmazonGreen.jpg",
    "sourceLabel": "388-AmazonGreen",
    "legacyPreserved": false
  },
  {
    "id": "demo-101-gloss",
    "code": "101",
    "name": "White",
    "finish": "gloss",
    "decorId": "d101",
    "colourFamily": "white",
    "swatch": "/media/swatches/101-gloss.jpg",
    "displayHex": "#f5f5f0",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/02_101-White-copy-1.jpg",
    "sourceLabel": "101-White",
    "legacyPreserved": false
  },
  {
    "id": "demo-540-gloss",
    "code": "540",
    "name": "Alpinweiß",
    "finish": "gloss",
    "decorId": "d540",
    "colourFamily": "white",
    "swatch": "/media/swatches/540-gloss.jpg",
    "displayHex": "#f1f3f0",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/04_540-Alpinweiss-copy-1.jpg",
    "sourceLabel": "540-Alpinweiß",
    "legacyPreserved": false
  },
  {
    "id": "demo-545-gloss",
    "code": "545",
    "name": "White",
    "finish": "gloss",
    "decorId": "d545",
    "colourFamily": "white",
    "swatch": "/media/swatches/545-gloss.jpg",
    "displayHex": "#f3f3f1",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/05_545-White-copy-1.jpg",
    "sourceLabel": "545-White",
    "legacyPreserved": false
  },
  {
    "id": "demo-191-gloss",
    "code": "191",
    "name": "Kristallweiß",
    "finish": "gloss",
    "decorId": "d191",
    "colourFamily": "white",
    "swatch": "/media/swatches/191-gloss.jpg",
    "displayHex": "#edeee8",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/03_191-Kristallweiss-copy-1.jpg",
    "sourceLabel": "191-Kristallweiß",
    "legacyPreserved": false
  },
  {
    "id": "demo-8361-gloss",
    "code": "8361",
    "name": "LuxWhite",
    "finish": "gloss",
    "decorId": "d8361",
    "colourFamily": "white",
    "swatch": "/media/swatches/8361-gloss.jpg",
    "displayHex": "#e1e1dd",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/01_8361-LuxWhite-copy-1.jpg",
    "sourceLabel": "8361-LuxWhite",
    "legacyPreserved": false
  },
  {
    "id": "demo-544-gloss",
    "code": "544",
    "name": "White",
    "finish": "gloss",
    "decorId": "d544",
    "colourFamily": "white",
    "swatch": "/media/swatches/544-gloss.jpg",
    "displayHex": "#f6f8f5",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/06_544-White-copy-1.jpg",
    "sourceLabel": "544-White",
    "legacyPreserved": false
  },
  {
    "id": "demo-547-gloss",
    "code": "547",
    "name": "White",
    "finish": "gloss",
    "decorId": "d547",
    "colourFamily": "white",
    "swatch": "/media/swatches/547-gloss.jpg",
    "displayHex": "#eff0eb",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/08_547-White-copy-1.jpg",
    "sourceLabel": "547-White",
    "legacyPreserved": false
  },
  {
    "id": "demo-556-gloss",
    "code": "556",
    "name": "CallaWeiss",
    "finish": "gloss",
    "decorId": "d556",
    "colourFamily": "white",
    "swatch": "/media/swatches/556-gloss.jpg",
    "displayHex": "#f5f5ee",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/10_556-CallaWeiss-copy-1.jpg",
    "sourceLabel": "556-CallaWeiss",
    "legacyPreserved": false
  },
  {
    "id": "demo-594-gloss",
    "code": "594",
    "name": "White",
    "finish": "gloss",
    "decorId": "d594",
    "colourFamily": "white",
    "swatch": "/media/swatches/594-gloss.jpg",
    "displayHex": "#f3efe6",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/07_594-White-copy-1.jpg",
    "sourceLabel": "594-White",
    "legacyPreserved": false
  },
  {
    "id": "demo-238-gloss",
    "code": "238",
    "name": "White",
    "finish": "gloss",
    "decorId": "d238",
    "colourFamily": "white",
    "swatch": "/media/swatches/238-gloss.jpg",
    "displayHex": "#f2f0e5",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/09_238-White-copy-1.jpg",
    "sourceLabel": "238-White",
    "legacyPreserved": false
  },
  {
    "id": "demo-745-gloss",
    "code": "745",
    "name": "SilkWhite",
    "finish": "gloss",
    "decorId": "d745",
    "colourFamily": "white",
    "swatch": "/media/swatches/745-gloss.jpg",
    "displayHex": "#efeee2",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/11_745-SilkWhite-copy-1.jpg",
    "sourceLabel": "745-SilkWhite",
    "legacyPreserved": false
  },
  {
    "id": "demo-8362-gloss",
    "code": "8362",
    "name": "LuxMagnolie",
    "finish": "gloss",
    "decorId": "d8362-luxmagnolie",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/8362-gloss.jpg",
    "displayHex": "#eee7dc",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/12_8362-LuxMagnolie-copy-1.jpg",
    "sourceLabel": "8362-LuxMagnolie",
    "legacyPreserved": false
  },
  {
    "id": "demo-216-gloss",
    "code": "216",
    "name": "Cream",
    "finish": "gloss",
    "decorId": "d216",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/216-gloss.jpg",
    "displayHex": "#f2e7d6",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/13_216-Cream-copy-1.jpg",
    "sourceLabel": "216-Cream",
    "legacyPreserved": false
  },
  {
    "id": "demo-239-gloss",
    "code": "239",
    "name": "Magnolie",
    "finish": "gloss",
    "decorId": "d239",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/239-gloss.jpg",
    "displayHex": "#efe7da",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/14_239-Magnolie-copy-1.jpg",
    "sourceLabel": "239-Magnolie",
    "legacyPreserved": false
  },
  {
    "id": "demo-570-gloss",
    "code": "570",
    "name": "GiorgioSeta",
    "finish": "gloss",
    "decorId": "d570-giorgioseta",
    "colourFamily": "grey",
    "swatch": "/media/swatches/570-gloss.jpg",
    "displayHex": "#d6d2ce",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/15_570-GiorgioSeta-copy-1.jpg",
    "sourceLabel": "570-GiorgioSeta",
    "legacyPreserved": false
  },
  {
    "id": "demo-8368-gloss",
    "code": "8368",
    "name": "LuxSahara",
    "finish": "gloss",
    "decorId": "d8368",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/8368-gloss.jpg",
    "displayHex": "#ccc5bd",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/16_8368-LuxSahara-copy-1.jpg",
    "sourceLabel": "8368-LuxSahara",
    "legacyPreserved": false
  },
  {
    "id": "demo-962-gloss",
    "code": "962",
    "name": "Hellgrau",
    "finish": "gloss",
    "decorId": "d962",
    "colourFamily": "grey",
    "swatch": "/media/swatches/962-gloss.jpg",
    "displayHex": "#cecdcc",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/17_962-Hellgrau-2.jpg",
    "sourceLabel": "962-Hellgrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-211-gloss",
    "code": "211",
    "name": "Sandgrau",
    "finish": "gloss",
    "decorId": "d211",
    "colourFamily": "grey",
    "swatch": "/media/swatches/211-gloss.jpg",
    "displayHex": "#cbc4ba",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/18_211-Sandgrau-copy.jpg",
    "sourceLabel": "211-Sandgrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-236-gloss",
    "code": "236",
    "name": "GrigioPerla",
    "finish": "gloss",
    "decorId": "d236",
    "colourFamily": "grey",
    "swatch": "/media/swatches/236-gloss.jpg",
    "displayHex": "#afaca8",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/19_236-GrigioPerla-copy.jpg",
    "sourceLabel": "236-GrigioPerla",
    "legacyPreserved": false
  },
  {
    "id": "demo-412-gloss",
    "code": "412",
    "name": "GrisGalet",
    "finish": "gloss",
    "decorId": "d412-grisgalet",
    "colourFamily": "grey",
    "swatch": "/media/swatches/412-gloss.jpg",
    "displayHex": "#9f9f9d",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/20_412-GrisGalet-copy.jpg",
    "sourceLabel": "412-GrisGalet",
    "legacyPreserved": false
  },
  {
    "id": "demo-8363-gloss",
    "code": "8363",
    "name": "LuxQuarzgrau",
    "finish": "gloss",
    "decorId": "d8363",
    "colourFamily": "grey",
    "swatch": "/media/swatches/8363-gloss.jpg",
    "displayHex": "#787775",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/21_8363-LuxQuarzgrau-copy.jpg",
    "sourceLabel": "8363-LuxQuarzgrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-420-gloss",
    "code": "420",
    "name": "Gray",
    "finish": "gloss",
    "decorId": "d420",
    "colourFamily": "grey",
    "swatch": "/media/swatches/420-gloss.jpg",
    "displayHex": "#696665",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/22_420-Gray-1.jpg",
    "sourceLabel": "420-Gray",
    "legacyPreserved": false
  },
  {
    "id": "demo-425-gloss",
    "code": "425",
    "name": "SlateGrey",
    "finish": "gloss",
    "decorId": "d425",
    "colourFamily": "grey",
    "swatch": "/media/swatches/425-gloss.jpg",
    "displayHex": "#4f5550",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/23_425-SlateGrey-copy.jpg",
    "sourceLabel": "425-SlateGrey",
    "legacyPreserved": true
  },
  {
    "id": "demo-3355-gloss",
    "code": "3355",
    "name": "Carbon",
    "finish": "gloss",
    "decorId": "d3355",
    "colourFamily": "black",
    "swatch": "/media/swatches/3355-gloss.jpg",
    "displayHex": "#515151",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/25_3355-Carbon-copy.jpg",
    "sourceLabel": "3355-Carbon",
    "legacyPreserved": false
  },
  {
    "id": "demo-567-gloss",
    "code": "567",
    "name": "Black",
    "finish": "gloss",
    "decorId": "d567",
    "colourFamily": "black",
    "swatch": "/media/swatches/567-gloss.jpg",
    "displayHex": "#2e2f30",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/26_567-Black-copy.jpg",
    "sourceLabel": "567-Black",
    "legacyPreserved": false
  },
  {
    "id": "demo-373-gloss",
    "code": "373",
    "name": "OliveGreen",
    "finish": "gloss",
    "decorId": "d373",
    "colourFamily": "green",
    "swatch": "/media/swatches/373-gloss.jpg",
    "displayHex": "#737956",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/27_373-OliveGreen-copy.jpg",
    "sourceLabel": "373-OliveGreen",
    "legacyPreserved": true
  },
  {
    "id": "demo-8366-gloss",
    "code": "8366",
    "name": "LuxYellow",
    "finish": "gloss",
    "decorId": "d8366",
    "colourFamily": "yellow",
    "swatch": "/media/swatches/8366-gloss.jpg",
    "displayHex": "#fbe275",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/28_8366-LuxYellow-copy.jpg",
    "sourceLabel": "8366-LuxYellow",
    "legacyPreserved": false
  },
  {
    "id": "demo-515-gloss",
    "code": "515",
    "name": "Orange",
    "finish": "gloss",
    "decorId": "d515",
    "colourFamily": "orange",
    "swatch": "/media/swatches/515-gloss.jpg",
    "displayHex": "#b8674c",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/29_515-Orange-copy.jpg",
    "sourceLabel": "515-Orange",
    "legacyPreserved": false
  },
  {
    "id": "demo-414-gloss",
    "code": "414",
    "name": "Rouge",
    "finish": "gloss",
    "decorId": "d414",
    "colourFamily": "red",
    "swatch": "/media/swatches/414-gloss.jpg",
    "displayHex": "#b92130",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/30_414-Rouge-copy.jpg",
    "sourceLabel": "414-Rouge",
    "legacyPreserved": false
  },
  {
    "id": "demo-932-gloss",
    "code": "932",
    "name": "Red",
    "finish": "gloss",
    "decorId": "d932",
    "colourFamily": "red",
    "swatch": "/media/swatches/932-gloss.jpg",
    "displayHex": "#99243a",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/31_932-Red-copy.jpg",
    "sourceLabel": "932-Red",
    "legacyPreserved": false
  },
  {
    "id": "demo-571-gloss",
    "code": "571",
    "name": "BlueNotte",
    "finish": "gloss",
    "decorId": "d571",
    "colourFamily": "blue",
    "swatch": "/media/swatches/571-gloss.jpg",
    "displayHex": "#2c3a48",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/32_571-BlueNotte-copy.jpg",
    "sourceLabel": "571-BlueNotte",
    "legacyPreserved": false
  },
  {
    "id": "demo-8364-gloss",
    "code": "8364",
    "name": "LuxLila",
    "finish": "gloss",
    "decorId": "d8364",
    "colourFamily": "purple",
    "swatch": "/media/swatches/8364-gloss.jpg",
    "displayHex": "#917da5",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/33_8364-LuxLila-copy.jpg",
    "sourceLabel": "8364-LuxLila",
    "legacyPreserved": false
  },
  {
    "id": "demo-580-gloss",
    "code": "580",
    "name": "Beige",
    "finish": "gloss",
    "decorId": "d580",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/580-gloss.jpg",
    "displayHex": "#d0c8b9",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/34_580-Beige-copy.jpg",
    "sourceLabel": "580-Beige",
    "legacyPreserved": false
  },
  {
    "id": "demo-1104-gloss",
    "code": "1104",
    "name": "Kieselgrau",
    "finish": "gloss",
    "decorId": "d1104",
    "colourFamily": "grey",
    "swatch": "/media/swatches/1104-gloss.jpg",
    "displayHex": "#aca49e",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/35_1104-Kieselgrau-copy.jpg",
    "sourceLabel": "1104-Kieselgrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-1115-gloss",
    "code": "1115",
    "name": "Cubanit",
    "finish": "gloss",
    "decorId": "d1115",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/1115-gloss.jpg",
    "displayHex": "#ccc9be",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/36_1115-Cubanit-copy.jpg",
    "sourceLabel": "1115-Cubanit",
    "legacyPreserved": false
  },
  {
    "id": "demo-6091-gloss",
    "code": "6091",
    "name": "Mocca",
    "finish": "gloss",
    "decorId": "d6091",
    "colourFamily": "brown",
    "swatch": "/media/swatches/6091-gloss.jpg",
    "displayHex": "#aca79c",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/37_6091-Mocca-copy.jpg",
    "sourceLabel": "6091-Mocca",
    "legacyPreserved": false
  },
  {
    "id": "demo-8367-gloss",
    "code": "8367",
    "name": "LuxLava",
    "finish": "gloss",
    "decorId": "d8367",
    "colourFamily": "brown",
    "swatch": "/media/swatches/8367-gloss.jpg",
    "displayHex": "#b9a394",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/38_8367-LuxLava-copy.jpg",
    "sourceLabel": "8367-LuxLava",
    "legacyPreserved": false
  },
  {
    "id": "demo-1106-gloss",
    "code": "1106",
    "name": "Sandgrau",
    "finish": "gloss",
    "decorId": "d1106",
    "colourFamily": "grey",
    "swatch": "/media/swatches/1106-gloss.jpg",
    "displayHex": "#a49b92",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/39_1106-Sandgrau-copy.jpg",
    "sourceLabel": "1106-Sandgrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-413-gloss",
    "code": "413",
    "name": "BrunTaupe",
    "finish": "gloss",
    "decorId": "d413",
    "colourFamily": "brown",
    "swatch": "/media/swatches/413-gloss.jpg",
    "displayHex": "#a69d95",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/40_413-BrunTaupe-copy.jpg",
    "sourceLabel": "413-BrunTaupe",
    "legacyPreserved": false
  },
  {
    "id": "demo-242-gloss",
    "code": "242",
    "name": "BasaltGrau",
    "finish": "gloss",
    "decorId": "d242",
    "colourFamily": "grey",
    "swatch": "/media/swatches/242-gloss.jpg",
    "displayHex": "#8f877e",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/42_242-BasaltGrau-copy.jpg",
    "sourceLabel": "242-BasaltGrau",
    "legacyPreserved": false
  },
  {
    "id": "demo-477-gloss",
    "code": "477",
    "name": "Cacao",
    "finish": "gloss",
    "decorId": "d477",
    "colourFamily": "brown",
    "swatch": "/media/swatches/477-gloss.jpg",
    "displayHex": "#7f7369",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/43_477-Cacao-copy.jpg",
    "sourceLabel": "477-Cacao",
    "legacyPreserved": false
  },
  {
    "id": "demo-1108-gloss",
    "code": "1108",
    "name": "Terra",
    "finish": "gloss",
    "decorId": "d1108",
    "colourFamily": "brown",
    "swatch": "/media/swatches/1108-gloss.jpg",
    "displayHex": "#4a413f",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/44_1108-Terra-copy.jpg",
    "sourceLabel": "1108-Terra",
    "legacyPreserved": false
  },
  {
    "id": "demo-7451-gloss",
    "code": "7451",
    "name": "SilkyWhite",
    "finish": "gloss",
    "decorId": "d7451",
    "colourFamily": "white",
    "swatch": "/media/swatches/7451-gloss.jpg",
    "displayHex": "#e7ddc2",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/45_7451-SilkyWhite.jpg",
    "sourceLabel": "7451-SilkyWhite",
    "legacyPreserved": false
  },
  {
    "id": "demo-4981-gloss",
    "code": "4981",
    "name": "SandBeige",
    "finish": "gloss",
    "decorId": "d4981",
    "colourFamily": "neutral",
    "swatch": "/media/swatches/4981-gloss.jpg",
    "displayHex": "#8e8070",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/46_4981-SandBeige.jpg",
    "sourceLabel": "4981-SandBeige",
    "legacyPreserved": false
  },
  {
    "id": "demo-5660-gloss",
    "code": "5660",
    "name": "AnthrazitgrauPearl",
    "finish": "gloss",
    "decorId": "d5660",
    "colourFamily": "grey",
    "swatch": "/media/swatches/5660-gloss.jpg",
    "displayHex": "#403b36",
    "sourceImageUrl": "https://www.finedecor.de/wp-content/uploads/2020/11/47_5660-AnthrazitgrauPearl.jpg",
    "sourceLabel": "5660-AnthrazitgrauPearl",
    "legacyPreserved": false
  }
];

// Cosmetic spelling differences such as weiss/weiß share a decor. Materially
// different names under 412/570/8362 stay separate until owner reconciliation.
export const productionDecors: Decor[] = Array.from(new Map(productionSourceEntries.map(entry => [entry.decorId, {
  id: entry.decorId, code: entry.code, name: productionSourceEntries.find(item => item.decorId === entry.decorId)!.name,
  colourFamily: entry.colourFamily, source: PRODUCTION_CATALOG_SOURCE,
}])).values());

// Added source swatches have no approved material maps or 3D preview asset.
// Their display hex is an indicative thumbnail average, never a measured colour.
export const productionVariants: ProductVariant[] = productionSourceEntries.filter(entry => !entry.legacyPreserved).map(entry => ({
  id: entry.id, decorId: entry.decorId, finishId: entry.finish,
  familyId: null, sku: null, approval: 'draft', demo: true,
  compatibleApplications: [], dimensions: null, documentIds: [],
  materialId: null, swatch: entry.swatch, hex: entry.displayHex,
}));
