PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS ProductFamily(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Decor(id TEXT PRIMARY KEY,code TEXT NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Finish(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ProductVariant(id TEXT PRIMARY KEY,decor_id TEXT NOT NULL REFERENCES Decor(id),finish_id TEXT NOT NULL REFERENCES Finish(id),family_id TEXT REFERENCES ProductFamily(id),sku TEXT,payload TEXT NOT NULL,UNIQUE(decor_id,finish_id));
CREATE TABLE IF NOT EXISTS Application(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS VariantApplication(variant_id TEXT REFERENCES ProductVariant(id),application_id TEXT REFERENCES Application(id),approval TEXT NOT NULL,PRIMARY KEY(variant_id,application_id));
CREATE TABLE IF NOT EXISTS MediaAsset(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS MaterialAsset(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS TechnicalDocument(id TEXT PRIMARY KEY,approval TEXT NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ClaimEvidence(id TEXT PRIMARY KEY,approval TEXT NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Office(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS NewsArticle(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS UserRole(id TEXT PRIMARY KEY,role TEXT UNIQUE NOT NULL,token_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Project(id TEXT PRIMARY KEY,owner_hash TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ShareToken(token_hash TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES Project(id),created_at TEXT NOT NULL,expires_at TEXT NOT NULL,revoked_at TEXT);
CREATE TABLE IF NOT EXISTS SampleRequest(id TEXT PRIMARY KEY,owner_hash TEXT NOT NULL,idempotency_key TEXT NOT NULL,payload TEXT NOT NULL,body_hash TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(owner_hash,idempotency_key));
CREATE TABLE IF NOT EXISTS Outbox(id TEXT PRIMARY KEY,request_id TEXT NOT NULL REFERENCES SampleRequest(id),adapter TEXT NOT NULL,status TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,next_attempt TEXT,UNIQUE(request_id,adapter));
CREATE TABLE IF NOT EXISTS ContentRevision(id TEXT PRIMARY KEY,variant_id TEXT NOT NULL REFERENCES ProductVariant(id),payload TEXT NOT NULL,status TEXT NOT NULL,created_by TEXT NOT NULL,reviewed_by TEXT,review_payload TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS AuditEvent(id TEXT PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,record_id TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS RateLimit(key_hash TEXT PRIMARY KEY,count INTEGER NOT NULL,reset_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_project_owner ON Project(owner_hash);
CREATE INDEX IF NOT EXISTS idx_share_project ON ShareToken(project_id);
CREATE INDEX IF NOT EXISTS idx_outbox_status ON Outbox(status,next_attempt);
CREATE INDEX IF NOT EXISTS idx_request_owner ON SampleRequest(owner_hash);
PRAGMA optimize;
