import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {createHash,randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import {families,decors,finishes,variants,applications,materials,offices,news,evidence,mediaAssets} from './catalog';
import type {UserRole} from './model';
export const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
let database:DatabaseSync|undefined;
export function db(){if(database)return database;const dir=process.env.FD_DATA_DIR||join(process.cwd(),'.local-data');mkdirSync(dir,{recursive:true,mode:0o700});database=new DatabaseSync(join(dir,'finedecor.sqlite'));database.exec(readFileSync(join(process.cwd(),'lib/schema.sql'),'utf8'));for(const [table,rows] of Object.entries({ProductFamily:families,Decor:decors,Finish:finishes,Application:applications,MaterialAsset:materials,MediaAsset:mediaAssets,Office:offices,NewsArticle:news})){for(const r of rows as {id:string}[]){if(table==='Decor'){database.prepare('INSERT OR IGNORE INTO Decor(id,code,payload) VALUES(?,?,?)').run(r.id,(r as typeof decors[number]).code,JSON.stringify(r))}else{database.prepare(`INSERT OR IGNORE INTO ${table}(id,payload) VALUES(?,?)`).run(r.id,JSON.stringify(r))}}}for(const v of variants)database.prepare('INSERT OR IGNORE INTO ProductVariant(id,decor_id,finish_id,family_id,sku,payload) VALUES(?,?,?,?,?,?)').run(v.id,v.decorId,v.finishId,v.familyId,v.sku,JSON.stringify(v));for(const c of evidence)database.prepare('INSERT OR IGNORE INTO ClaimEvidence(id,approval,payload) VALUES(?,?,?)').run(c.id,c.approval,JSON.stringify(c));for(const role of ['editor','technical','administrator'] as const){const token=process.env[`FD_${role.toUpperCase()}_TOKEN`];if(token)database.prepare('INSERT INTO UserRole(id,role,token_hash) VALUES(?,?,?) ON CONFLICT(role) DO UPDATE SET token_hash=excluded.token_hash').run(role,role,hash(token))}return database;}
export function transaction<T>(fn:()=>T):T{const d=db();d.exec('BEGIN IMMEDIATE');try{const result=fn();d.exec('COMMIT');return result}catch(e){d.exec('ROLLBACK');throw e}}
export function actor(req:Request):UserRole|null{const token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token||token.length>200)return null;const h=hash(token);const r=db().prepare('SELECT role,token_hash FROM UserRole').all() as unknown as {role:UserRole;token_hash:string}[];return r.find(x=>timingSafeEqual(Buffer.from(x.token_hash),Buffer.from(h)))?.role||null}
export function session(req:Request){const existing=req.headers.get('cookie')?.match(/(?:^|;\s*)fd_session=([a-f0-9]{64})(?:;|$)/)?.[1];const token=existing||randomBytes(32).toString('hex');return {owner:hash(token),cookie:existing?null:`fd_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000${new URL(req.url).protocol==='https:'?'; Secure':''}`}}
export function rateLimit(key:string,limit=40){const d=db(),now=Date.now();const r=d.prepare('SELECT count,reset_at FROM RateLimit WHERE key_hash=?').get(hash(key)) as {count:number;reset_at:number}|undefined;if(!r||r.reset_at<now){d.prepare('INSERT OR REPLACE INTO RateLimit VALUES(?,?,?)').run(hash(key),1,now+60000);return true}if(r.count>=limit)return false;d.prepare('UPDATE RateLimit SET count=count+1 WHERE key_hash=?').run(hash(key));return true}
export function audit(actor:string,action:string,record:string){db().prepare('INSERT INTO AuditEvent VALUES(?,?,?,?,?)').run(randomUUID(),actor,action,record,new Date().toISOString())}
export function ownProject(id:string,owner:string){return db().prepare('SELECT * FROM Project WHERE id=? AND owner_hash=?').get(id,owner) as {id:string;payload:string;created_at:string}|undefined}
