import {z} from 'zod';
import {getVariant,applications} from './catalog';
const id=z.string().max(80).refine(x=>!!getVariant(x),'Variant is missing or unavailable');
const vec=z.tuple([z.number().finite().min(-30).max(30),z.number().finite().min(-30).max(30),z.number().finite().min(-30).max(30)]);
export const projectSchema=z.object({name:z.string().trim().min(1).max(80),variantIds:z.array(id).min(1).max(12).refine(a=>new Set(a).size===a.length,'Duplicate variant IDs'),assignments:z.object({fronts:id,accent:id.optional()}).strict(),scene:z.enum(['panel','kitchen','unit']),light:z.enum(['neutral','daylight','warm']),camera:z.object({preset:z.enum(['perspective','front','detail']),position:vec,target:vec}).strict().refine(c=>Math.hypot(...c.position.map((v,i)=>v-c.target[i]))>.25,'Camera is too close to target'),compareId:id.nullable()}).strict().superRefine((p,c)=>{for(const v of Object.values(p.assignments)){if(!p.variantIds.includes(v))c.addIssue({code:'custom',message:'Assignment must be in project variant IDs'})}if(p.scene==='panel'&&p.assignments.accent)c.addIssue({code:'custom',message:'Panel supports the fronts slot only'});if(p.compareId&&!p.variantIds.includes(p.compareId))c.addIssue({code:'custom',message:'Comparison must be in project variant IDs'})});
export const requestSchema=z.object({name:z.string().trim().min(2).max(100),company:z.string().trim().min(2).max(150),email:z.string().trim().email().max(180),country:z.string().trim().min(2).max(80),application:z.enum([...applications.map(a=>a.id),'other'] as unknown as [string,...string[]]),details:z.string().trim().min(10).max(3000),kind:z.enum(['samples','technical']),variantIds:z.array(id).max(12).refine(a=>new Set(a).size===a.length),projectId:z.string().uuid().nullable(),serviceAcknowledgement:z.literal(true),website:z.string().max(0),locale:z.enum(['en','de']),idempotencyKey:z.string().uuid()}).strict().superRefine((p,c)=>{if(p.kind==='samples'&&!p.variantIds.length)c.addIssue({code:'custom',message:'Select a variant to request samples'})});
export const draftSchema=z.object({variantId:id,editorialLabel:z.string().trim().min(3).max(100),note:z.string().trim().min(10).max(1500)}).strict();
const validDate=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s,'Invalid calendar date');
export const approvalSchema=z.object({decision:z.enum(['approve','hold']),evidenceUrl:z.string().url().max(500).refine(s=>s.startsWith('https://'),'Use an HTTPS evidence URL'),documentVersion:z.string().min(1).max(50),issueDate:validDate,reviewDate:validDate,rightsConfirmed:z.literal(true),scopeConfirmed:z.literal(true)}).strict().refine(v=>v.reviewDate>=v.issueDate,'Review date must follow issue date');
